Achievement 2/Exercise 2.1/src/books/urls.py
from django.urls import path
from .views import BookListView, BookDetailView

app_name = 'books'

urlpatterns = [
    path('list/', BookListView.as_view(), name='list'),
    path('list/<pk>', BookDetailView.as_view(), name='detail'),
]

Achievement 2/Exercise 2.1/src/bookstore/urls.py
"""
URL configuration for bookstore project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path, include  # Make sure to import include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls')),  # Include sales app URLs at root
    path('books/', include('books.urls')),  # Include books app URLs
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Achievement 2/Exercise 2.1/src/books/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
genre_choices = (
    ('classic', 'Classic'), 
    ('romantic', 'Romantic'), 
    ('comic', 'Comic'), 
    ('fantasy', 'Fantasy'), 
    ('horror', 'Horror'), 
    ('educational', 'Educational'),
)

book_type_choices = (
    ('hardcover', 'Hard cover'),
    ('ebook', 'E-Book'),
    ('audiobook', 'Audiobook')
)

class Book(models.Model):
    name = models.CharField(max_length=120)
    author_name = models.CharField(max_length=120)
    price = models.FloatField(help_text='in US dollars $')
    genre = models.CharField(max_length=12, choices=genre_choices, default='cl')
    book_type = models.CharField(max_length=12, choices=book_type_choices, default='hc')
    pic = models.ImageField(upload_to='books', default='no_picture.jpg')

    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
        return reverse('books:detail', kwargs={'pk': self.pk})

Achievement 2/Exercise 2.1/src/books/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Book
# to protect class-based view
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class BookListView(LoginRequiredMixin, ListView):  # class-based "protected" view
    model = Book
    template_name = 'books/main.html'

class BookDetailView(LoginRequiredMixin, DetailView):  # class-based "protected" view
    model = Book
    template_name = 'books/detail.html'

Achievement 2/Exercise 2.1/src/books/templates/books/detail.html
<h2>Details: {{object.name}}</h2>

<b>Title: </b> {{object.name}} <br>

<b>Author: </b> {{object.author_name}} <br>

<b>Genre: </b> {{object.genre}} <br>

<b>Book Type: </b> {{object.book_type}} <br>

<b>Price: </b> ${{object.price}} <br>

<br>
<img src="{{object.pic.url}}" width="200" height="300" />

<br><br>
<a href="{% url 'books:list' %}">Back to Books List</a>

Achievement 2/Exercise 2.1/src/books/templates/books/main.html
<h1>Books' list</h1>

<a href="{% url 'logout' %}">Logout</a>

<table border="1" cellpadding="5" cellspacing="5">
    <tr>
        <td><b>Books' Titles</b></td>
        <td><b>Books' Images</b></td>
    </tr>
    {% for object in object_list %}
    <tr>
        <td><a href="{{object.get_absolute_url}}">{{object.name}}</a></td>
        <td><img src="{{object.pic.url}}" width="150" height="200" /></td>
    </tr>
    {% endfor %}
</table>